### ISSUE TITLE
No longer works?

### ISSUE THREAD

**Issue by mbrownnycnyc** [motasay/YouTube-Download#1]
Hello,

I have attempted to use this on several computers, and it no longer works with an HTTP error 303 (forbidden).

Can this be confirmed?

Thanks,

Matt

**Comment by motasay** [comment]
Just tested the bookmarklet on Safari and the chrome extension. Both are working.

Are you using the latest source? Could you please specify the browser, the URL and which one is not working, the bookmarklet, the extension or both?

Mota
